easy_admin:
    entities:
      CarouselClash:
          class: App\Entity\CarouselClash
          disabled_actions: [new, edit, delete]

          list:
              actions: [show]

              fields:
                - createdAt
                - url
                - name

          show:
              fields:
                - createdAt
                - url
                - name
                - property: data
                  template: admin/CarouselClash/show/data.html.twig
